name: tfsec sarif
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: Run tfsec with sarif upload
        uses: aquasecurity/tfsec-sarif-action@v0.1.3
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
