name: tfsec

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  tfsec:
    name: tfsec scan
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.2
